version: '3.8'

services:
  tinksrv:
    image: tinksrv
    build:
      context: src/tinksrv
      dockerfile: ./Dockerfile
    expose:
      - 8081
    secrets:
      - tinksrv_kek
  backend:
    image: backend
    build:
      context: src
      dockerfile: backend/Dockerfile
    expose:
      - 8080
    ports:
      - "8080:8080"

secrets:
  tinksrv_kek:
    file: src/tinksrv/configs/keyset.json
