version: '3.8'

services:
  tinksrv:
    image: tinksrv
    build:
      context: src/tinksrv
      dockerfile: ./Dockerfile
    expose:
      - 8001
  backend:
    image: backend
    build:
      context: src/backend
      dockerfile: ./Dockerfile
    expose:
      - 8080
