apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      labels:
        io.kompose.network/g8keeper-default: "true"
        io.kompose.service: backend
    spec:
      containers:
        - image: backend
          imagePullPolicy: IfNotPresent
          name: backend
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /configs
              name: vol-cm-backend
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      restartPolicy: Always
      volumes:
        - name: vol-cm-backend
          configMap:
            name: cm-backend
