apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-tinksrv
data:
  config.toml: |
    [log]
    level = "info"

    [app]
    name = "tinksrv"
    port = "8081"

    [kms]
    kekFile = "/run/secrets/tinksrv-kek"
