apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: tinksrv
  name: tinksrv
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tinksrv
  template:
    metadata:
      labels:
        io.kompose.network/g8keeper-default: "true"
        io.kompose.service: tinksrv
    spec:
      containers:
        - image: tinksrv
          imagePullPolicy: IfNotPresent
          name: tinksrv
          ports:
            - containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /run/secrets
              name: vol-tinksrv-kek
      restartPolicy: Always
      volumes:
        - name: vol-tinksrv-kek
          secret:
            secretName: tinksrv-kek
            items:
              - key: tinksrv-kek
                path: tinksrv-kek
