apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: tinksrv
  name: tinksrv
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tinksrv
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/k8s-password-manager-default: "true"
        io.kompose.service: tinksrv
    spec:
      containers:
        - image: tinksrv
          imagePullPolicy: IfNotPresent
          name: tinksrv
          ports:
            - containerPort: 8001
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "250m"
      restartPolicy: Always
